### PR TITLE
fix, always show LEER MÁS

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
hm. then shouldnt we put a word max on the excerpt? in the pdf its 162 words each post

**Comment by mixcas** [comment]
@mikeyrayvon true, doing it on this branch

**Comment by mixcas** [comment]
how to cut the text? with `…` ?

**Comment by mikeyrayvon** [comment]
i just talked to santiago. we should do a separate text field for the excerpt

**Comment by mikeyrayvon** [comment]
so `if_single() { the_excerpt() } else { the_content() }`

**Comment by mixcas** [comment]
@mikeyrayvon that exist in WP already tho :)
no need to create new field

**Comment by mikeyrayvon** [comment]
i knowwwwwwwwwwwwwwwww

**Comment by mixcas** [comment]
yeeeiiiiii :DDDD

**Comment by mixcas** [comment]
@mikeyrayvon ready, check n merge plz

**Pull request merged**
