### PR TITLE
Scaffold programacion

### PR DESCRIPTION
**Pull request by varffs**
archive & single

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
weve got `col-l-#` declared twice in site.styl

**Comment by mikeyrayvon** [comment]
i dont get how you have this set up.  where is the archive page?

**Comment by varffs** [comment]
`/programacion`

**Comment by mikeyrayvon** [comment]
so i guess the slider is coming in another branch?

**Comment by varffs** [comment]
yep

**Pull request merged**
