### PR TITLE
Improve type

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by mixcas** [comment]
whats the scope of this PR? Im wondering because there's font styles that are missing still. E.g. Sans font in programacion single's content.

**Comment by mixcas** [comment]
E.g. `#header-menu` links have a weight of 600 while in the pdf looks more like it should be 500

**Comment by mikeyrayvon** [comment]
the links in header menu have a weight of 500

**Comment by mikeyrayvon** [comment]
the scope of this PR is to fix all the type so tell me whats missing

**Comment by mixcas** [comment]
@mikeyrayvon my bad, idk why my branch was so behind if i had just cloned it… checking now

**Comment by mikeyrayvon** [comment]
`gulp` ?

**Comment by mixcas** [comment]
idk, i think i might have branched out earlier or somthing, i just had to pull. its working now.

Imma be adding comments with what i see, so u can fixit as i'm checking
- Spacing between _No._, title and subtitle in /programacion

**Comment by mixcas** [comment]
I think the font size of the content in Citas is diff

**Comment by mikeyrayvon** [comment]
i think the font-sizing strategy site-wide is a little fucked

**Comment by mixcas** [comment]
@mikeyrayvon that's what i was thinking

**Comment by mixcas** [comment]
subtitle in /programacion should be italics

**Comment by mixcas** [comment]
i think that's it. everything else look pristine. 
@mikeyrayvon lmk when u fix those up there ^^  i can check/merge

**Comment by mikeyrayvon** [comment]
screen shot 2016-09-12 at 6 14 58 pm
not always italics :/

**Comment by mikeyrayvon** [comment]
i think we should leave the Citas content type the same size as in Nosotros. makes sense they would be the same. and see what they say?

**Comment by mixcas** [comment]
@mikeyrayvon LOL with the italics…

kk, this ready for merge? (im asking :P )

**Comment by mikeyrayvon** [comment]
yes

**Pull request merged**
