### PR TITLE
Style front page

### PR DESCRIPTION
**Pull request by varffs**
Only 1 question remains about if the verticle centering of the latest programacion post should be done using js or this solution which uses 60vh

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
the CASA LUIS BARRAGAN of the splash doesnt line up with that of the footer.  problem?

**Comment by varffs** [comment]
@mikeyrayvon you mean vertically or horizontally?

**Comment by mikeyrayvon** [comment]
verticlaly

**Comment by varffs** [comment]
i dont think it is a problem. yes we could offset the vertical location of that text to match the footer, but I think it would look weird so I'd rather they bring it up if they dont like how it is now

**Pull request merged**
