### PR TITLE
Feature conditional header

### PR DESCRIPTION
**Pull request by varffs**
a bit of a mess like the design tbh. but works according to the pdf

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
i really dont understand what the header design is supposed to do

**Comment by mikeyrayvon** [comment]
can you walk me through it?

**Comment by varffs** [comment]
Yh it is really unclear so my conditionals are:

`if (!is_page('home'))` : show no links on home

`if ($post && is_single_type('programacion', $post))` : show (currently) all program posts via their number on single program

`else if (!is_page('home') && !is_post_type_archive('programacion'))` : if isn't home page OR program archive show the links for about [called home in the design] with the section links (like press etc which will be scrollers or something) and the 'noticias' section

You need to set a front page and a posts page called noticias for the site to work

**Comment by varffs** [comment]
:/

**Comment by mikeyrayvon** [comment]
really curious about how its supposed to look when there are more programaccion posts than will fit in that 6 col

**Comment by mikeyrayvon** [comment]
you have an idea bout thtat?

**Comment by varffs** [comment]
Yeah I'm gonna ask them. Also it makes no sense cus 01 is the first but surely it needs to be the latest program post which could be like 14 or something

**Comment by varffs** [comment]
This design got more holes than swiss cheese

**Pull request merged**
